services:
    ursim:
        image: universalrobots/ursim_e-series:5.9.4
        environment:
            - ROBOT_MODEL=UR5
        ports:
            - "5900:5900" # VNC
            - "6080:6080" # Web GUI
            - "30003:30003" # Real Time
            - "30004:30004" # RTDE
        stdin_open: true
        tty: true
        restart: "no"
        volumes:
            - "./programs:/ursim/programs"
        platform: linux/amd64
